- name: Home Assistant Bootstrap
  hosts: homeassistant
  gather_facts: false
  tasks:
    - name: Install Python
      ansible.builtin.raw: apk add --no-cache python3 rsync curl
      changed_when: "'Installing' in result.stdout"
      register: result

- name: Home Assistant Setup
  hosts: homeassistant
  gather_facts: true
  roles:
    - dotfiles
    - git_config
  tasks:
    - name: Source dotfiles shell config from bash_profile
      ansible.builtin.blockinfile:
        path: /data/.bash_profile
        block: |
          export SHELL_DIR=~/dotfiles/shell
          source $SHELL_DIR/config

    - name: Sync backups to peque
      ansible.builtin.cron:
        name: "sync home assistant backups to peque"
        minute: "0"
        hour: "*/12"
        job: "rsync -az --delete /backup/ {{ peque_user }}@{{ peque_host }}:{{ peque_backup_path }}/homeassistant/ && curl -fsS -m 10 --retry 5 https://hc-ping.com/{{ healthchecks_ping_key }}/home-assistant-backups"
