all:
  children:
    linux:
      hosts:
        dev-machine:
          ansible_host: localhost
          ansible_connection: local
    homeassistant:
      hosts:
        hassio:
          ansible_host: 192.168.1.134
          ansible_user: root
    osx:
      children:
        osx_desktop:
          hosts:
            macbook:
              ansible_host: localhost
              ansible_connection: local
              ansible_user: ivan
        osx_agent:
          hosts:
            osx-agent:
              ansible_host: 192.168.1.71
              ansible_user: clawdbot
              ansible_ssh_common_args: "-o ForwardAgent=yes"
