- name: config neovim
  hosts: localhost
  become: no
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "~/apps"
        state: directory
        mode: "0755"
    - name: download neovim
      ansible.builtin.get_url:
        url: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage"
        dest: "~/apps/nvim"
        mode: "770"
    - name: create directory if it does not exist
      ansible.builtin.file:
        path: "~/.config"
        state: directory
    - name: Creating hardlink
      ansible.builtin.file:
        src: "~/dotfiles/nvim"
        dest: "~/.config/nvim"
        state: link
