- name: configure dock bar
  hosts: localhost
  become: false
  vars:
    remove:
      - Contacts
      - Maps
      - Photos
      - FaceTime
      - Keynote
      - Calendar
      - Preview
      - Reminders
      - TV
      - Music
      - Podcasts
      - Safari
      - Messages
      - Mail
      - Freeform
      - Launchpad
    add:
      - "/Applications/Google Chrome.app"
      - "/Applications/Spotify.app"
      - "/Applications/Google Drive.app"
  tasks:
    - name: Remove applications from dock
      shell: "dockutil --remove '{{ item }}' --no-restart"
      ignore_errors: true
      with_items: "{{ remove }}"
      when: remove
      changed_when: false

    - name: Add applications from dock
      shell: "dockutil --add '{{ item }}' --no-restart"
      ignore_errors: true
      with_items: "{{ add }}"
      when: add
      changed_when: false

    - name: Reduce the size of the Dock
      shell: defaults write com.apple.dock tilesize -int 50

    - name: Restart dock
      shell: killall Dock
