- name: check if dotfiles git config exists
  ansible.builtin.stat:
    path: "~/dotfiles/git/.gitconfig"
  register: dotfiles_gitconfig

- name: creating symlink for git config
  ansible.builtin.file:
    src: "~/dotfiles/git/.gitconfig"
    dest: "~/.gitconfig"
    state: link
  when: dotfiles_gitconfig.stat.exists

- name: create git identity override
  ansible.builtin.copy:
    content: |
      [user]
        name = {{ git_user_name }}
        email = {{ git_user_email }}
    dest: "~/.gitconfig.local"
    mode: "0644"
  when: git_user_name | length > 0

- name: install gitleaks (apt)
  become: true
  ansible.builtin.apt:
    name: gitleaks
    state: present
  when: ansible_os_family == "Debian"

- name: install gitleaks (brew)
  community.general.homebrew:
    name: gitleaks
    state: present
  when: ansible_os_family == "Darwin"
