- name: check if miniconda is already installed
  stat:
    path: "{{ ansible_env.HOME }}/miniconda3/bin/conda"
  register: conda_binary

- name: create miniconda directory
  file:
    path: "{{ ansible_env.HOME }}/miniconda3"
    state: directory
  when: not conda_binary.stat.exists

- name: download miniconda
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: "{{ ansible_env.HOME }}/miniconda3/miniconda.sh"
    mode: "0755"
  when: not conda_binary.stat.exists

- name: install miniconda
  command:
    cmd: "bash {{ ansible_env.HOME }}/miniconda3/miniconda.sh -b -u -p {{ ansible_env.HOME }}/miniconda3"
  when: not conda_binary.stat.exists

- name: clean up installer
  file:
    path: "{{ ansible_env.HOME }}/miniconda3/miniconda.sh"
    state: absent
