- name: Install apt-transport-https
  ansible.builtin.apt:
    state: latest
    update_cache: true
  become: true

- name: ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Add Google Chrome apt signing key
  ansible.builtin.get_url:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    dest: /etc/apt/keyrings/google-chrome.asc
    owner: root
    group: root
    mode: "0644"
    force: false
  become: true

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.asc] https://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome
  become: true

- name: Install google-chrome-stable
  ansible.builtin.apt:
    name: "google-chrome-stable"
    state: latest
    update_cache: true
  become: true
